### PR TITLE
WIP: Experiments for batched evaluation in ACE1x.jl

### PR DESCRIPTION
**Pull request by cortner**
this branch is required to work with the `evaluator` branch in `ACE1x.jl`

### CODE REVIEW

**Comment by cortner** [comment]
@tjjarvinen  -- you asked to be pointed to the memory access problem. With the change I suggested it is partially resolved: 

https://github.com/ACEsuit/ACEcore.jl/blob/bcdf0c37d29173a751be122ff5f8b6c10356ebfc/src/sparseprod.jl#L141

**Comment by cortner** [comment]
Screen Shot 2023-01-09 at 1 29 23 PM

as you see the bottleneck has now moved to the n-correlations, which is good. Here, I think it will be harder to fix the memory access cost. I thought this would be better because of the linear access pattern...

**Comment by cortner** [comment]
@wcwitt  --- I've just pushed a new profiling script to `ACEcore/profile/profAA/profile_AA.jl` which is a minimal test case for you to explore.

**Comment by wcwitt** [comment]
Hi @cortner, thanks for the script, I've adapted it to compare with the C++ kernels: https://github.com/wcwitt/ace.cpp/blob/main/test/profile_AA.jl.

Julia and C++ are in the same ballpark for both non-batched and batched, which is good. Julia does slightly worse for Real and slightly better for Complex, which is curious. Eventually I'll figure out the reason.

Here is some example output:
```
[ Info: Loading C++ module
[ Info: Basic test of PIPotential construction and evaluation
length(basis) = 33349
non-batched benchmark:
 complex      :   48.967 μs (0 allocations: 0 bytes)
    real      :   33.258 μs (0 allocations: 0 bytes)

 complex (cpp):   62.833 μs (0 allocations: 0 bytes)
    real (cpp):   26.433 μs (0 allocations: 0 bytes)
Test Passed
Test Passed
batched benchmark with batch-size 32:
 complex      :   1.398 ms (0 allocations: 0 bytes)
    real      :   433.983 μs (0 allocations: 0 bytes)

 complex (cpp):   1.563 ms (0 allocations: 0 bytes)
    real (cpp):   420.117 μs (0 allocations: 0 bytes)
Test Passed
Test Passed
```

**Comment by cortner** [comment]
VERY interesting, thank you. I'm really surprised that C++ can beat Julia in the real benchmark by this much.

**Comment by cortner** [comment]
I think the next step is to test the pullback for the AA basis, which is a little more complex. After that we move to the pooling and so on.

**Comment by cortner** [comment]
I'm merging this into main without actually merging the PR as I need some of this in BIPs.jl

**Pull request merged**
